# Example of sample specific Kconfig changes when building sample with MCUboot
# when using sysbuild. Note that the MCUboot operating mode is not set here as
# sysbuild will automatically set it for both the application and MCUboot images itself
CONFIG_MCUBOOT_LOG_LEVEL_WRN=y
CONFIG_MCUBOOT_DOWNGRADE_PREVENTION=n
# CONFIG_BOOT_SIGNATURE_TYPE_NONE=y

# CONFIG_LOG=n
# CONFIG_CONSOLE=n
# CONFIG_UART_CONSOLE=n

# # MCUboot serial configuration
# CONFIG_MCUBOOT_SERIAL=y
# CONFIG_BOOT_SERIAL_UART=y
# CONFIG_BOOT_SERIAL_ENTRANCE_GPIO=n
# CONFIG_BOOT_SERIAL_WAIT_FOR_DFU=y
# CONFIG_BOOT_SERIAL_NO_APPLICATION=y
# CONFIG_BOOT_SERIAL_WAIT_FOR_DFU_TIMEOUT=5000

# CONFIG_ESP_FLASH_SIZE=2MB
# CONFIG_ESP_BOOTLOADER_SIZE=0xF000
# CONFIG_ESP_BOOTLOADER_OFFSET=0x0000
# CONFIG_ESP_IMAGE0_PRIMARY_START_ADDRESS=0x10000
# CONFIG_ESP_APPLICATION_SIZE=0xF0000
# CONFIG_ESP_IMAGE0_SECONDARY_START_ADDRESS=0x100000
# CONFIG_ESP_MCUBOOT_WDT_ENABLE=y
# CONFIG_ESP_SCRATCH_OFFSET=0x1F0000
# CONFIG_ESP_SCRATCH_SIZE=0x10000

CONFIG_BOOT_BANNER=y
