CONFIG_GPIO=y

CONFIG_RUST=y
CONFIG_RUST_ALLOC=y

CONFIG_DEBUG=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=72000

CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000

CONFIG_GPIO_ENABLE_DISABLE_INTERRUPT=y

#Verify that userspace builds work.
#CONFIG_USERSPACE=y

CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=n

CONFIG_CONSOLE=y

CONFIG_MODBUS=y
CONFIG_MODBUS_ROLE_CLIENT_SERVER=y

CONFIG_LOG=y
#CONFIG_LOG_DEFAULT_LEVEL=4

CONFIG_CAN=y
CONFIG_CAN_MAX_FILTER=8
CONFIG_ISOTP=y
CONFIG_ISOTP_RX_SF_FF_BUF_COUNT=1

#CONFIG_SAMPLE_LOOPBACK_MODE=y

CONFIG_GPIO_PCF857X=y
CONFIG_AUXDISPLAY=y
CONFIG_BUILD_OUTPUT_HEX=y

# General config
CONFIG_SHELL=y
CONFIG_LOG=y
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_INIT_STACKS=y
CONFIG_ZVFS_OPEN_MAX=32
CONFIG_POSIX_API=y
CONFIG_FDTABLE=y
CONFIG_ZVFS_POLL_MAX=32

# Eventfd
CONFIG_EVENTFD=y

# Networking config
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_NET_SHELL=y
CONFIG_NET_STATISTICS=y
CONFIG_NET_STATISTICS_USER_API=y
CONFIG_NET_LOG=y

CONFIG_WIFI=y
# Network buffers
CONFIG_NET_PKT_RX_COUNT=16
CONFIG_NET_PKT_TX_COUNT=16
CONFIG_NET_BUF_RX_COUNT=128
CONFIG_NET_BUF_TX_COUNT=128
CONFIG_NET_CONTEXT_NET_PKT_POOL=y

# IP address options
CONFIG_NET_IF_UNICAST_IPV6_ADDR_COUNT=3
CONFIG_NET_IF_MCAST_IPV6_ADDR_COUNT=4
CONFIG_NET_MAX_CONTEXTS=32
CONFIG_NET_MAX_CONN=32

CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y

CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_NEED_IPV6=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.1.7"
CONFIG_NET_CONFIG_MY_IPV4_NETMASK="255.255.255.0"
CONFIG_NET_CONFIG_MY_IPV4_GW="192.168.1.1"

CONFIG_IDLE_STACK_SIZE=1024
CONFIG_ISR_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_NET_TCP_TIME_WAIT_DELAY=200


# Network debug config
CONFIG_NET_SOCKETS_LOG_LEVEL_DBG=n
CONFIG_NET_HTTP_LOG_LEVEL_DBG=n
CONFIG_NET_IPV6_LOG_LEVEL_DBG=n
CONFIG_NET_IPV6_ND_LOG_LEVEL_DBG=n

CONFIG_NET_CONFIG_INIT_TIMEOUT=2

CONFIG_MINIMAL_LIBC=y
CONFIG_MINIMAL_LIBC_RAND=y
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=72000

CONFIG_SYS_HEAP_RUNTIME_STATS=y
CONFIG_SHELL_CMDS=y
CONFIG_NET_SOCKETS_POLL_MAX=16
CONFIG_NET_DHCPV4=y
CONFIG_NET_L2_ETHERNET=y
#------------------

# CONFIG_NET_DEBUG_NET_PKT_ALLOC=y
# CONFIG_NET_BUF_POOL_USAGE=y
# CONFIG_KERNEL_SHELL=y
# CONFIG_THREAD_MONITOR=y
# CONFIG_THREAD_RUNTIME_STATS=y
# CONFIG_THREAD_RUNTIME_STATS_USE_TIMING_FUNCTIONS=y
# CONFIG_STATS=y
# CONFIG_STATS_SHELL=y
# CONFIG_DATE_SHELL=y
# CONFIG_THREAD_NAME=y
# CONFIG_DEVICE_SHELL=y
# CONFIG_THREAD_STACK_INFO=y
# CONFIG_INIT_STACKS=y
# CONFIG_NET_TCP_LOG_LEVEL_DBG=y
# CONFIG_NET_MGMT=y
# CONFIG_NET_STATISTICS=y
# CONFIG_NET_STATISTICS_IPV4=y
# CONFIG_NET_STATISTICS_USER_API=y
# CONFIG_NET_MGMT_EVENT_MONITOR=y
# CONFIG_NET_CONNECTION_MANAGER=y
# CONFIG_NET_SOCKETS_OBJ_CORE=y
# CONFIG_OBJ_CORE=y
# CONFIG_STACK_SENTINEL=y
# CONFIG_ASSERT=y

# CONFIG_NET_TCP_MAX_SEND_WINDOW_SIZE=16384
# CONFIG_NET_TCP_MAX_RECV_WINDOW_SIZE=16384


